version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jobboard-postgres
    restart: always
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ff_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobboard-backend
    ports:
      - "8080:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/jobboard
      JWT_SECRET: secret
      PORT: 5000
      NODE_ENV: production
    # ЗАКОММЕНТИРУЙТЕ volumes на время сборки
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  ff_postgres_data:
  backend_node_modules: